name: ActivityRoles
version: ${project.version}
main: com.shadowdev.activityroles.ActivityRoles
api-version: 1.20
author: thewilloftheshadow
depend: [DiscordSRV]
load: POSTWORLD
website: "https://github.com/buape/ActivityRoles"
description: Automatically give and remove Discord roles from players based on their play time within your server.
permissions:
    activityroles.check:
        default: true
        description: Allows the usage of /activity
    activityroles.lastonline:
        default: true
        description: Allows the usage of /lastonline
commands:
    activity:
        usage: /activity
        permission: activityroles.check
        description: Check and resync your activity roles
    lastonline:
        usage: /lastonline
        permission: activityroles.lastonline
        description: Check when you last played on the server
        arguments:
            - player:
                  description: The player to check
                  type: player
                  optional: false
